// =============================================================================
// GridSense AI - ML Client Service
// Orchestrates calls to the Python ML prediction service with a resilient fallback.
// =============================================================================

const ML_SERVICE_URL = process.env.ML_SERVICE_URL || 'http://127.0.0.1:8000';

/**
 * Deterministic physics-informed baseline fallback model.
 * Models electrical contingency sensitivities when Python ML service is offline.
 */
function calculateFallbackRisk(data) {
  const solar = Number(data.solar_mw);
  const wind = Number(data.wind_mw);
  const load = Number(data.load_mw);
  const voltage = Number(data.voltage_pu);
  const frequency = Number(data.frequency_hz);
  const ramp = Number(data.renewable_ramp_pct || 0);
  const reactive = Number(data.reactive_power_mvar || 100);

  const totalRenewable = solar + wind;
  const penetration = load > 0 ? totalRenewable / load : 0;
  const netDemand = load - totalRenewable;
  const nominalFreq = frequency > 55 ? 60.0 : 50.0;
  const freqDev = Math.abs(frequency - nominalFreq);
  const voltDev = Math.abs(voltage - 1.0);

  // Inertia deficit proxy: high penetration displaces synchronous rotational mass
  const inertiaFactor = Math.max(0, penetration - 0.5) * 0.22;
  const rampStress = (ramp / 25.0) * 0.20;
  const freqStress = freqDev * 3.8;
  const voltStress = voltDev * 2.5;
  const overgenStress = netDemand < 0 ? 0.20 : 0;

  // Compute composite risk score [0.00 - 1.00]
  let rawScore = 0.12 + freqStress + voltStress + inertiaFactor + rampStress + overgenStress;
  const riskScore = Number(Math.min(0.98, Math.max(0.04, rawScore)).toFixed(3));

  // Risk categorization according to application rules
  let riskLevel = 'LOW';
  let mitigationNotes = 'Normal grid conditions. Standard spinning reserve and voltage regulation active.';

  if (riskScore >= 0.80) {
    riskLevel = 'CRITICAL';
    mitigationNotes = 'Severe contingency alert. High likelihood of under-frequency or voltage instability. Engage immediate fast-start peaker reserves and BESS dynamic response.';
  } else if (riskScore >= 0.65) {
    riskLevel = 'HIGH';
    mitigationNotes = 'Elevated operational risk detected. High renewable ramp or frequency droop requires spinning reserve dispatch and inverter VAR adjustment.';
  } else if (riskScore >= 0.35) {
    riskLevel = 'MODERATE';
    mitigationNotes = 'Moderate grid stress. Heightened monitoring recommended on critical interconnection ties.';
  }

  // Parameter contributions breakdown for explainability
  const contributingFactors = {
    frequency_deviation: Number(freqDev.toFixed(3)),
    voltage_deviation: Number(voltDev.toFixed(3)),
    renewable_penetration: Number(penetration.toFixed(3)),
    ramp_stress: Number((ramp / 25.0).toFixed(3)),
    net_demand_mw: Math.round(netDemand)
  };

  return {
    riskScore,
    riskLevel,
    confidence: 0.89,
    contributingFactors,
    mitigationNotes,
    modelVersion: 'v0.1.0-physics-baseline',
    modelStatus: 'demo_fallback (Python ML offline)'
  };
}

async function predictGridRisk(scenarioData) {
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 2000);

    const response = await fetch(`${ML_SERVICE_URL}/predict`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        solar: Number(scenarioData.solar_mw),
        wind: Number(scenarioData.wind_mw),
        load: Number(scenarioData.load_mw),
        voltage: Number(scenarioData.voltage_pu),
        frequency: Number(scenarioData.frequency_hz),
        ramp: Number(scenarioData.renewable_ramp_pct || 0),
        reactive: Number(scenarioData.reactive_power_mvar || 100),
        load_variation: Number(scenarioData.load_variation_pct || 0)
      }),
      signal: controller.signal
    });

    clearTimeout(timeoutId);

    if (response.ok) {
      const mlResult = await response.json();
      return {
        riskScore: mlResult.risk_score,
        riskLevel: mlResult.risk_level,
        confidence: mlResult.confidence || 0.91,
        contributingFactors: mlResult.contributing_factors || {},
        mitigationNotes: mlResult.mitigation_notes || 'Generated by Python ML prediction service.',
        modelVersion: mlResult.model_version || 'v0.1.0-scikit-learn',
        modelStatus: 'python_ml_active'
      };
    }
  } catch (err) {
    // Python ML service unreachable or timed out - use physics-informed fallback
  }

  return calculateFallbackRisk(scenarioData);
}

module.exports = {
  predictGridRisk,
  calculateFallbackRisk
};
